<?php

declare(strict_types=1);

namespace App\Infrastructure\YouTube;

use App\Domain\YouTube\Exception\YouTubeImporterException;
use App\Domain\YouTube\YouTubeCaptionFetcherInterface;
use App\Domain\YouTube\YouTubeCaptionKind;
use App\Domain\YouTube\YouTubeCaptionResult;
use App\Domain\YouTube\YouTubeUrl;
use Symfony\Component\Process\Process;

final class YtDlpYouTubeCaptionFetcher implements YouTubeCaptionFetcherInterface
{
    public function __construct(
        private readonly string $binary,
    ) {
    }

    public function fetchOriginalCaptions(string $url, ?string $originalLanguage): ?YouTubeCaptionResult
    {
        YouTubeUrl::assertValid($url);

        $language = $this->normalizeLanguage($originalLanguage);

        if (null === $language) {
            return null;
        }

        $manual = $this->downloadCaptions($url, $language, false);

        if (null !== $manual) {
            return $manual;
        }

        return $this->downloadCaptions($url, $language, true);
    }

    private function downloadCaptions(string $url, string $language, bool $autoGenerated): ?YouTubeCaptionResult
    {
        $tempDir = sys_get_temp_dir().'/lumen-yt-captions-'.bin2hex(random_bytes(8));

        if (!mkdir($tempDir, 0775, true) && !is_dir($tempDir)) {
            throw new YouTubeImporterException('Unable to create caption download directory.');
        }

        try {
            $args = [
                $this->binary,
                '--skip-download',
                '--sub-langs',
                $language,
                '--sub-format',
                'json3',
                '--output',
                $tempDir.'/%(id)s',
            ];

            if ($autoGenerated) {
                $args[] = '--write-auto-subs';
            } else {
                $args[] = '--write-subs';
            }

            $args[] = $url;

            $process = new Process($args);
            $process->setTimeout(180);
            $process->run();

            if (!$process->isSuccessful()) {
                return null;
            }

            $files = glob($tempDir.'/*.'.$language.'.json3') ?: glob($tempDir.'/*.json3') ?: [];

            if ([] === $files) {
                return null;
            }

            $content = file_get_contents($files[0]);

            if (!is_string($content) || '' === trim($content)) {
                return null;
            }

            $segments = $this->parseJson3($content);

            if ([] === $segments) {
                return null;
            }

            return new YouTubeCaptionResult(
                $autoGenerated ? YouTubeCaptionKind::Auto : YouTubeCaptionKind::Manual,
                $language,
                $segments,
            );
        } finally {
            foreach (glob($tempDir.'/*') ?: [] as $file) {
                if (is_file($file)) {
                    @unlink($file);
                }
            }
            @rmdir($tempDir);
        }
    }

    /**
     * @return list<array{index: int, start: float, end: float, text: string}>
     */
    private function parseJson3(string $json): array
    {
        try {
            /** @var array<string, mixed> $decoded */
            $decoded = json_decode($json, true, 512, JSON_THROW_ON_ERROR);
        } catch (\JsonException) {
            return [];
        }

        $events = $decoded['events'] ?? [];

        if (!is_array($events)) {
            return [];
        }

        $segments = [];
        $index = 0;

        foreach ($events as $event) {
            if (!is_array($event)) {
                continue;
            }

            $startMs = is_numeric($event['tStartMs'] ?? null) ? (float) $event['tStartMs'] : null;
            $durationMs = is_numeric($event['dDurationMs'] ?? null) ? (float) $event['dDurationMs'] : 0.0;

            if (null === $startMs) {
                continue;
            }

            $text = $this->extractEventText($event);

            if ('' === $text) {
                continue;
            }

            $start = $startMs / 1000;
            $end = $start + ($durationMs / 1000);

            $segments[] = [
                'index' => $index,
                'start' => $start,
                'end' => max($end, $start + 0.1),
                'text' => $text,
            ];
            ++$index;
        }

        return $segments;
    }

    /**
     * @param array<string, mixed> $event
     */
    private function extractEventText(array $event): string
    {
        $segments = $event['segs'] ?? [];

        if (!is_array($segments)) {
            return '';
        }

        $parts = [];

        foreach ($segments as $segment) {
            if (!is_array($segment)) {
                continue;
            }

            $utf8 = $segment['utf8'] ?? '';

            if (is_string($utf8) && '' !== trim($utf8)) {
                $parts[] = trim($utf8);
            }
        }

        return trim(implode('', $parts));
    }

    private function normalizeLanguage(?string $language): ?string
    {
        if (null === $language || '' === trim($language)) {
            return 'en';
        }

        return strtolower(substr(trim($language), 0, 2));
    }
}
