# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:
    worker.base_url: '%env(WORKER_BASE_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Presentation\:
        resource: '../src/Presentation/'

    App\Application\:
        resource: '../src/Application/'

    App\Infrastructure\:
        resource: '../src/Infrastructure/'

    App\Domain\Content\ContentRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Content\DoctrineContentRepository

    App\Domain\Processing\ProcessingJobRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Processing\DoctrineProcessingJobRepository

    App\Application\Processing\Ports\ProcessingOrchestratorInterface:
        alias: App\Infrastructure\Processing\HttpWorkerDispatcher

    App\Infrastructure\Processing\HttpWorkerDispatcher:
        arguments:
            $workerBaseUrl: '%worker.base_url%'

    App\Shared\:
        resource: '../src/Shared/'
