import type { Artifact } from "@/services/artifact/types";

export const artifactMocksByContentId: Record<string, Artifact[]> = {
	"1": [
		{
			id: "artifact-transcript-1",
			contentId: "1",
			processingJobId: "1",
			type: "transcript",
			content: "The Roman Empire was a vast civilization.",
			createdAt: "2026-06-26T12:00:00+00:00",
		},
		{
			id: "artifact-summary-1",
			contentId: "1",
			processingJobId: "1",
			type: "summary",
			content:
				"This is a simulated summary generated by the processing worker.",
			createdAt: "2026-06-26T12:00:01+00:00",
		},
	],
};
