import type { Artifact } from "@/services/artifact/types";

export const artifactMocksByContentId: Record<string, Artifact[]> = {
	"1": [
		{
			id: "artifact-1",
			contentId: "1",
			processingJobId: "1",
			type: "summary",
			content:
				"This is a simulated summary generated by the processing worker.",
			createdAt: "2026-06-26T12:00:00+00:00",
		},
	],
};
