from unittest.mock import MagicMock, patch

from app.repositories.SymfonyApiRepository import SymfonyApiRepository


def test_start_calls_internal_endpoint() -> None:
    response = MagicMock()
    response.raise_for_status = MagicMock()

    with patch("httpx.post", return_value=response) as mock_post:
        repository = SymfonyApiRepository(base_url="http://backend")
        repository.start("job-123")

    mock_post.assert_called_once_with(
        "http://backend/internal/processing-jobs/job-123/start",
        json=None,
        headers={"Accept": "application/json"},
        timeout=30.0,
    )


def test_update_progress_sends_json_body() -> None:
    response = MagicMock()
    response.raise_for_status = MagicMock()

    with patch("httpx.post", return_value=response) as mock_post:
        repository = SymfonyApiRepository(base_url="http://backend")
        repository.update_progress("job-123", 42)

    mock_post.assert_called_once_with(
        "http://backend/internal/processing-jobs/job-123/progress",
        json={"progress": 42},
        headers={"Accept": "application/json"},
        timeout=30.0,
    )


def test_create_artifact_calls_internal_endpoint() -> None:
    response = MagicMock()
    response.raise_for_status = MagicMock()
    response.json.return_value = {
        "id": "artifact-789",
        "type": "summary",
        "createdAt": "2026-06-26T14:30:00+00:00",
    }

    summary_content = (
        "This is a simulated summary generated by the processing worker."
    )

    with patch("httpx.post", return_value=response) as mock_post:
        repository = SymfonyApiRepository(base_url="http://backend")
        result = repository.create_artifact(
            content_id="content-456",
            processing_job_id="job-123",
            artifact_type="summary",
            content=summary_content,
        )

    mock_post.assert_called_once_with(
        "http://backend/internal/artifacts",
        json={
            "contentId": "content-456",
            "processingJobId": "job-123",
            "type": "summary",
            "content": summary_content,
        },
        headers={"Accept": "application/json"},
        timeout=30.0,
    )
    assert result == {
        "id": "artifact-789",
        "type": "summary",
        "createdAt": "2026-06-26T14:30:00+00:00",
    }
