export const NAV_ICONS: Record<string, string> = {
	dashboard: "🏠",
	upload: "🎥",
	import: "📄",
	workspace: "📁",
	"pipeline-settings": "⚙️",
	"ai-engines": "🤖",
	transcript: "📜",
	translations: "🌍",
	audio: "🔊",
	"voice-clone": "🎙",
	"lip-sync": "🎬",
	render: "🎞",
	shadow: "🌑",
	library: "📚",
	collections: "🗂",
	"settings-hub": "🔧",
};
