ARTIFACT_TYPE_SUMMARY = "summary"
ARTIFACT_TYPE_QUIZ = "quiz"
ARTIFACT_TYPE_FLASHCARDS = "flashcards"
ARTIFACT_TYPE_TIMELINE = "timeline"
ARTIFACT_TYPE_TRANSLATION = "translation"
ARTIFACT_TYPE_PODCAST = "podcast"
ARTIFACT_TYPE_MIND_MAP = "mind_map"

SUPPORTED_ARTIFACT_TYPES = frozenset({
    ARTIFACT_TYPE_SUMMARY,
    ARTIFACT_TYPE_QUIZ,
    ARTIFACT_TYPE_FLASHCARDS,
})

FUTURE_ARTIFACT_TYPES = frozenset({
    ARTIFACT_TYPE_TIMELINE,
    ARTIFACT_TYPE_TRANSLATION,
    ARTIFACT_TYPE_PODCAST,
    ARTIFACT_TYPE_MIND_MAP,
})
